name: User Story
description: Funktion aus Sicht eines Nutzers
title: "US: "
labels: ["user-story", "mvp"]

body:
  - type: input
    id: story_id
    attributes:
      label: User Story ID
      description: Nummer oder Kürzel der User Story
      placeholder: "z. B. US1, US2, US3"
    validations:
      required: true

  - type: input
    id: parent_feature
    attributes:
      label: Zugehöriges Feature
      description: Zu welchem Feature gehört diese User Story?
      placeholder: "z. B. Feature: Pre-Check-Formular"
    validations:
      required: true

  - type: textarea
    id: user_story
    attributes:
      label: User Story
      description: Formuliere die Story aus Sicht des Nutzers.
      value: "Als [Rolle] möchte ich [Funktion], damit [Nutzen]."
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Beschreibung
      description: Was soll fachlich umgesetzt werden?
      placeholder: "Kurze Beschreibung der gewünschten Funktion."
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: Akzeptanzkriterien
      description: Wann ist die User Story erfüllt?
      value: |
        - [ ] 
        - [ ] 
        - [ ] 
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: Mögliche Tasks
      description: Welche technischen Aufgaben könnten daraus entstehen?
      value: |
        - [ ] 
        - [ ] 
        - [ ] 
    validations:
      required: false
